{
  "openapi": "3.0.1",
  "info": {
    "title": "Checkout.com API Reference",
    "description": "# Introduction\nCheckout.com provides a collection of APIs that enable you to process and manage payments.  \nOur APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors. You can consume the APIs directly using your favorite HTTP/REST library or, if you'd like to make use of one of our SDKs, please let our Integration team know at <a href=\"mailto:integration@checkout.com\" target=\"_blank\">integration@checkout.com</a>.  \n\nOur unified[...]",
    "termsOfService": "https://checkout.com/terms/",
    "contact": {
      "name": "Checkout.com Support",
      "url": "https://checkout.com",
      "email": "support@checkout.com"
    },
    "license": {
      "name": "Checkout.com",
      "url": "https://checkout.com/api/license/"
    },
    "version": "1.0.0",
    "x-logo": {
      "url": "https://assets.checkout.com/docs/logos/logo-checkout-api-dark.svg",
      "backgroundColor": "#E6E7EC",
      "altText": "Checkout.com API logo"
    }
  },
  "servers": [
    {
      "url": "https://api.checkout.com",
      "description": "Live API"
    },
    {
      "url": "https://api.sandbox.checkout.com",
      "description": "Sandbox API"
    }
  ],
  "paths": {
    "/connect/token": {
      "post": {
        "tags": [
          "Access"
        ],
        "summary": "Request an access token",
        "description": "OAuth endpoint to exchange your access key ID and access key secret for an access token."
      },
      "servers": [
        {
          "url": "https://access.checkout.com",
          "description": "Live API"
        },
        {
          "url": "https://access.sandbox.checkout.com",
          "description": "Sandbox API"
        }
      ]
    },
    "/disputes": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "Get disputes",
        "description": "Returns a list of all disputes against your business. The results will be returned in reverse chronological order, showing the last modified dispute (for example, where you've recently added a piece of evidence) first. You can use the optional parameters below to skip or limit results.",
        "security": [
          {
            "OAuth": [
              "disputes",
              "disputes:view"
            ]
          }
        ]
      }
    },
    "/disputes/{dispute_id}": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "Get dispute details",
        "description": "Returns all the details of a dispute using the dispute identifier.",
        "security": [
          {
            "OAuth": [
              "disputes",
              "disputes:view"
            ]
          }
        ]
      }
    },
    "/disputes/{dispute_id}/accept": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "Accept dispute",
        "description": "If a dispute is legitimate, you can choose to accept it. This will close it for you and remove it from your list of open disputes. There are no further financial implications.",
        "security": [
          {
            "OAuth": [
              "disputes",
              "disputes:accept"
            ]
          }
        ]
      }
    },
    "/disputes/{dispute_id}/evidence": {
      "put": {
        "tags": [
          "Disputes"
        ],
        "summary": "Provide dispute evidence",
        "description": "Adds supporting evidence to a dispute. Before using this endpoint, you first need to [upload your files](#tag/Disputes/paths/~1files/post) using the file uploader. You will receive a file id (prefixed by `file_`) which you can then use in your request. Note that this only attaches the evidence to the dispute, it does not send it to us. Once ready, you will need to submit it. **You must provide at least one evidence type in the body of your request.**\n",
        "security": [
          {
            "OAuth": [
              "disputes",
              "disputes:provide-evidence"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "Get dispute evidence",
        "description": "Retrieves a list of the evidence submitted in response to a specific dispute. \n",
        "security": [
          {
            "OAuth": [
              "disputes",
              "disputes:view"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "Submit dispute evidence",
        "description": "With this final request, you can submit the evidence that you have previously provided. Make sure you have provided all the relevant information before using this request. You will not be able to amend your evidence once you have submitted it.",
        "security": [
          {
            "OAuth": [
              "disputes",
              "disputes:provide-evidence"
            ]
          }
        ]
      }
    },
    "/files": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "Upload file",
        "description": "Upload a file to use as evidence in a dispute. Your file must be in either JPEG/JPG, PNG or PDF format, and be no larger than 4MB.",
        "security": [
          {
            "OAuth": [
              "disputes",
              "disputes:provide-evidence"
            ]
          }
        ]
      }
    },
    "/files/{file_id}": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "Get file information",
        "description": "Retrieve information about a file that was previously uploaded.",
        "security": [
          {
            "OAuth": [
              "disputes",
              "disputes:view"
            ]
          }
        ]
      }
    },
    "/workflows": {
      "get": {
        "tags": [
          "Workflows"
        ],
        "summary": "Get all workflows",
        "description": "Get all workflows\n",
        "security": [
          {
            "OAuth": [
              "flow",
              "flow:workflows"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Workflows"
        ],
        "summary": "Add a workflow",
        "description": "Add a new Flow workflow\n",
        "security": [
          {
            "OAuth": [
              "flow",
              "flow:workflows"
            ]
          }
        ]
      }
    },
    "/workflows/{workflowId}": {
      "get": {
        "tags": [
          "Workflows"
        ],
        "summary": "Get a workflow",
        "description": "Get the details of a workflow\n",
        "security": [
          {
            "OAuth": [
              "flow",
              "flow:workflows"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Workflows"
        ],
        "summary": "Remove a workflow",
        "description": "Removes a workflow so it is no longer being executed. \nActions of already executed workflows will be still processed.\n"
      }
    },
    "/workflows/event-types": {
      "get": {
        "tags": [
          "Workflows"
        ],
        "summary": "Get event types",
        "description": "Get a list of sources and their events for building new workflows\n",
        "security": [
          {
            "OAuth": [
              "flow",
              "flow:workflows"
            ]
          }
        ]
      }
    },
    "/workflows/events/{eventId}": {
      "get": {
        "tags": [
          "Workflows"
        ],
        "summary": "Get an event",
        "description": "Get the details of an event\n",
        "security": [
          {
            "OAuth": [
              "flow",
              "flow:events"
            ]
          }
        ]
      }
    },
    "/workflows/events/subject/{subjectId}": {
      "get": {
        "tags": [
          "Workflows"
        ],
        "summary": "Get subject events",
        "description": "Get all events that relate to a specific subject\n",
        "security": [
          {
            "OAuth": [
              "flow",
              "flow:events"
            ]
          }
        ]
      }
    },
    "/forex/quotes": {
      "post": {
        "tags": [
          "Forex"
        ],
        "summary": "Request a quote",
        "description": "Request an exchange rate between a source and destination currency pair that will be used to process one or more payouts. You must submit a payout with the FX quote identifier before the quote expires. If the FX quote identifier is omitted from a payout, and the source and destination currencies differ, the current market exchange rate will be used.\n",
        "security": [
          {
            "OAuth": [
              "fx"
            ]
          }
        ]
      }
    },
    "/instruments": {
      "post": {
        "tags": [
          "Instruments"
        ],
        "summary": "Create an instrument",
        "description": "Create a bank account payment instrument that you can later use as the destination for one or more payouts. <br><br>The parameters you need to provide depend on the destination country and currency. See <a href=\"https://docs.checkout.com/pay-to-bank/payout-formatting\" target=\"_blank\">our docs</a> and the <a href=\"#tag/Instruments/paths/~1validation~1bank-accounts~1{country}~1{currency}/get\">GET endpoint below</a>.\n",
        "security": [
          {
            "OAuth": [
              "vault",
              "vault:instruments"
            ]
          }
        ]
      }
    },
    "/instruments/{id}": {
      "patch": {
        "tags": [
          "Instruments"
        ],
        "summary": "Update an instrument",
        "description": "Update a bank account payment instrument that you can later use as the destination for one or more payouts.\n",
        "security": [
          {
            "OAuth": [
              "vault",
              "vault:instruments"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Instruments"
        ],
        "summary": "Delete an instrument",
        "description": "Delete a payment instrument.\n",
        "security": [
          {
            "OAuth": [
              "vault",
              "vault:instruments"
            ]
          }
        ]
      }
    },
    "/marketplace/entities": {
      "post": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Onboard a sub-entity",
        "description": "Onboard a sub-entity, so they can start receiving payments. Upon creation, Checkout.com will run due diligence checks. \nIf the checks are successful, the payment capabilities for the sub-entity will be enabled and they can start receiving payments.\n",
        "security": [
          {
            "OAuth": [
              "marketplace"
            ]
          }
        ]
      }
    },
    "/marketplace/entities/{id}": {
      "get": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Get sub-entity details",
        "security": [
          {
            "OAuth": [
              "marketplace"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Update sub-entity details",
        "description": "You can update all fields under the ContactDetails, Profile, and Company objects. \nPlease note that when you update a sub-entity we may conduct further due diligence checks when necessary. During these checks, your payment capabilities will remain the same.\n",
        "security": [
          {
            "OAuth": [
              "marketplace"
            ]
          }
        ]
      }
    },
    "/payments": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Request a payment or payout",
        "description": "Send a payment or payout \n",
        "operationId": "requestAPaymentOrPayout",
        "security": [
          {
            "ApiSecretKey": [ ]
          }
        ]
      }
    },
    "/payments/{id}": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get payment details",
        "description": "Returns the details of the payment with the specified identifier string.\n\nIf the payment method requires a redirection to a third party (e.g., 3D Secure),\nthe redirect URL back to your site will include a `cko-session-id` query parameter\ncontaining a payment session ID that can be used to obtain the details of the payment, for example:\n\nhttp://example.com/success?cko-session-id=sid_ubfj2q76miwundwlk72vxt2i7q.\n",
        "security": [
          {
            "OAuth": [
              "gateway",
              "gateway:payment-details"
            ]
          }
        ]
      }
    },
    "/payments/{id}/actions": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get payment actions",
        "description": "Returns all the actions associated with a payment ordered by processing date in descending order (latest first).\n",
        "security": [
          {
            "OAuth": [
              "gateway",
              "gateway:payment-details"
            ]
          }
        ]
      }
    },
    "/payments/{id}/authorizations": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Increment authorization",
        "description": "Request an incremental authorization to increase the authorization amount or extend the authorization's validity period (Mastercard only).\n",
        "security": [
          {
            "OAuth": [
              "gateway",
              "gateway:payment-authorizations"
            ]
          }
        ]
      }
    },
    "/payments/{id}/captures": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Capture a payment",
        "description": "Captures a payment if supported by the payment method.\n\nFor card payments, capture requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the capture is successful.\n",
        "security": [
          {
            "OAuth": [
              "gateway",
              "gateway:payment-captures"
            ]
          }
        ]
      }
    },
    "/payments/{id}/refunds": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Refund a payment",
        "description": "Refunds a payment if supported by the payment method.\n\nFor card payments, refund requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the refund is successful.\n",
        "security": [
          {
            "OAuth": [
              "gateway",
              "gateway:payment-refunds"
            ]
          }
        ]
      }
    },
    "/payments/{id}/voids": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Void a payment",
        "description": "Voids a payment if supported by the payment method.\n\nFor card payments, void requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the void is successful.\n",
        "security": [
          {
            "OAuth": [
              "gateway",
              "gateway:payment-voids"
            ]
          }
        ]
      }
    },
    "/sessions": {
      "post": {
        "tags": [
          "Sessions"
        ],
        "summary": "Request a session",
        "description": "Create a payment session to authenticate a cardholder before requesting a payment.\nPayment sessions can be linked to one or more payments (in the case of recurring and other merchant-initiated payments).\n\nThe `next_actions` object in the response tells you which actions can be performed next. \n",
        "security": [
          {
            "OAuth": [
              "sessions:app",
              "sessions:browser"
            ]
          }
        ]
      }
    },
    "/sessions/{id}": {
      "get": {
        "tags": [
          "Sessions"
        ],
        "summary": "Get session details",
        "description": "Returns the details of the session with the specified identifier string.\n",
        "security": [
          {
            "OAuth": [
              "sessions:app",
              "sessions:browser"
            ]
          },
          {
            "SessionSecret": [ ]
          }
        ]
      }
    },
    "/sessions/{id}/collect-data": {
      "put": {
        "tags": [
          "Sessions"
        ],
        "summary": "Update a session",
        "description": "Update a session by providing information about the environment.",
        "security": [
          {
            "OAuth": [
              "sessions:app",
              "sessions:browser"
            ]
          },
          {
            "SessionSecret": [ ]
          }
        ]
      }
    },
    "/sessions/{id}/complete": {
      "post": {
        "tags": [
          "Sessions"
        ],
        "summary": "Complete a session",
        "description": "Completes a session by posting the the following request to the callback URL (only relevant for non hosted sessions):\n```\n{\n   \"session_id\": \"sid_llraltf4jlwu5dxdtprcv7ba5i\",\n   \"amount\" : 6540,\n   \"currency\": \"USD\",\n   \"status\": \"approved\",\n   \"authentication_type\": \"regular\",\n   \"authentication_category\": \"payment\",\n   \"reference\": \"ORD-5023-4E89\",\n   \"approved\": true,\n   \"protocol_version\": \"2.1.0\",\n   \"response_code\": \"Y\[...]",
        "security": [
          {
            "OAuth": [
              "sessions:app",
              "sessions:browser"
            ]
          },
          {
            "SessionSecret": [ ]
          }
        ]
      }
    },
    "/sessions/{id}/issuer-fingerprint": {
      "put": {
        "tags": [
          "Sessions"
        ],
        "summary": "Update session 3DS Method completion indicator",
        "description": "Update the session's 3DS Method completion indicator based on the result of accessing the 3DS Method URL.",
        "security": [
          {
            "OAuth": [
              "sessions:browser"
            ]
          },
          {
            "SessionSecret": [ ]
          }
        ]
      }
    },
    "/tokens": {
      "post": {
        "tags": [
          "Tokens"
        ],
        "summary": "Request a token",
        "description": "Exchange card details for a reference token that can be used later to request a card payment. Tokens are single use and expire after 15 minutes. \nTo create a token, please authenticate using your public key. \n\n**Please note:** You should only use this for testing purposes.\n",
        "security": [
          {
            "ApiPublicKey": [ ]
          }
        ]
      }
    },
    "/validation/bank-accounts/{country}/{currency}": {
      "get": {
        "tags": [
          "Instruments"
        ],
        "summary": "Get bank account field formatting",
        "description": "Returns the bank account field formatting required to create bank account instruments or perform payouts for the specified country and currency.\n",
        "security": [
          {
            "OAuth": [
              "payout:bank-details"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiPublicKey": {
        "type": "apiKey",
        "description": "Unless explicitly stated, all endpoints require authentication using OAuth.  Public keys should only be used in JavaScript or native applications.\n#### Format\n- Sandbox `pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxx`\n- Production `pk_xxxxxxxxxxxxxxxxxxxxxxxxxx`\n",
        "name": "Authorization",
        "in": "query"
      },
      "OAuth": {
        "type": "oauth2",
        "description": "For server-to-server communication, we support the OAuth 2.0 client credentials flow.\nWe will provide you with a set of access key credentials – an access key ID and secret – which you can exchange for an access token by calling the 'request an access token' endpoint below. \nYou will need to authenticate using basic authentication, using your access key ID and access key secret as your username and password:\n\n```\ncurl --location --request POST 'https://access.checkou[...]",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "See table above",
            "scopes": {
              "vault": "Access to all Vault resources",
              "vault:instruments": "Create instruments",
              "gateway": "Access to all Gateway resources",
              "gateway:payment": "Request payments",
              "gateway:payment-details": "Get payment details",
              "gateway:payment-authorizations": "Increment authorizations",
              "gateway:payment-voids": "Void payments",
              "gateway:payment-captures": "Capture payments",
              "gateway:payment-refunds": "Refund payments",
              "fx": "Foreign exchange services",
              "payouts:bank-details": "Get bank details",
              "sessions": "Access to all Sessions resources",
              "sessions:app": "App-based authentication",
              "sessions:browser": "Browser-based authentication",
              "disputes": "Access to all Disputes resources",
              "disputes:view": "View disputes",
              "disputes:provide-evidence": "Provide dispute evidence",
              "disputes:accept": "Accept disputes",
              "martketplace": "Manage sub-entities",
              "flow": "Access to all Flow resources",
              "flow:workflows": "Manage workflows",
              "flow:events": "Retrieve events"
            }
          }
        }
      },
      "SessionSecret": {
        "type": "apiKey",
        "description": "A base64 encoded value prefixed with `sek_` that gives access to client-side operations for a single authentication within the Sessions API. This value is returned as the `session_secret` when requesting a session. \n",
        "name": "Authorization",
        "in": "query"
      }
    }
  },
  "tags": [
    {
      "name": "Access"
    },
    {
      "name": "Payments",
      "description": "Process and manage payments from a variety of sources and to various destinations all within one integration."
    },
    {
      "name": "Tokens",
      "description": "Create a token that represents a card's details that you can later use to request a payment, without you having to process or store any sensitive information."
    },
    {
      "name": "Instruments",
      "description": "Capture your customers’ bank account information and securely store it in the Vault to use for future payouts."
    },
    {
      "name": "Forex",
      "description": "Checkout.com Foreign Exchange services"
    },
    {
      "name": "Disputes",
      "description": "Keep track of and act on your open disputes (also known as chargebacks) to submit the best possible response."
    },
    {
      "name": "Marketplace",
      "description": "Manage all your sub-entities (also known as sub-merchants) through one integration, globally."
    },
    {
      "name": "Sessions",
      "description": "Use Sessions to authenticate transactions with 3D Secure (3DS) and comply with Strong Customer Authentication (SCA) requirements."
    },
    {
      "name": "Workflows",
      "description": "Use Workflows to start receiving webhook notifications for your payments, disputes, and marketplace sub-entities."
    }
  ]
}