openapi: '3.0.1'
info:
  version: '1.0.0'
  title: Checkout.com API Reference
  x-logo:
    url: "https://assets.checkout.com/docs/logos/logo-checkout-api-dark.svg"
    backgroundColor: "#E6E7EC"
    altText: "Checkout.com API logo"
  contact:
    name: Checkout.com Support
    url: 'https://checkout.com'
    email: support@checkout.com
  license:
    name: Checkout.com
    url: 'https://checkout.com/api/license/'
  termsOfService: 'https://checkout.com/terms/'
  description: >
    # Introduction
    
    Checkout.com provides a collection of APIs that enable you to process and manage payments.  
    
    Our APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors.
    You can consume the APIs directly using your favorite HTTP/REST library or, if you'd like to make use of one of our SDKs, please let our Integration team know at <a href="mailto:integration@checkout.com" target="_blank">integration@checkout.com</a>.  
  

    Our unified payments API allows you to accept payments, as well as pay out to a variety of destinations, all using the same integration. 
    
    
    And with our workflow management, events and disputes APIs, you can keep on top of your transactions and react to any chargebacks, keeping your business running smoothly. 
    
    # Authentication
    
    When you sign up for an account, you are given a public API key, and an access key ID and secret for OAuth 2.0. You authenticate with our API by following the appropriate authentication flow, using either your API keys or your access key credentials.


    Unless explicitly stated, all endpoints require authentication using OAuth. Public keys should only be used in JavaScript or native applications.


    Never share your access key credentials or access tokens. Keep them guarded and secure.

servers:
  - url: https://api.checkout.com
    description: Live API
  - url: https://api.sandbox.checkout.com
    description: Sandbox API
tags:
  - name: Access
  - name: Payments
    description: Process and manage payments from a variety of sources and to various destinations all within one integration.
  # - name: Sources
  #   description: Create a payment source for a customer that you can use for one or more payments.
  - name: Tokens
    description: Create a token that represents a card's details that you can later use to request a payment, without you having to process or store any sensitive information.
  - name: Instruments
    description: Capture your customers’ bank account information and securely store it in the Vault to use for future payouts.
  - name: Forex
    description: Checkout.com Foreign Exchange services
  - name: Disputes
    description: Keep track of and act on your open disputes (also known as chargebacks) to submit the best possible response.
  - name: Marketplace
    description: Manage all your sub-entities (also known as sub-merchants) through one integration, globally.
  - name: Sessions
    description: Use Sessions to authenticate transactions with 3D Secure (3DS) and comply with Strong Customer Authentication (SCA) requirements.
  - name: Workflows
    description: Use Workflows to start receiving webhook notifications for your payments, disputes, and marketplace sub-entities.
  # - name: Files
  #   description: |
  #     Upload files to be used as input to other APIs

# x-tagGroups:
# - name: Flow
#   tags:
#     - Events
#     - Workflows
paths:
  /connect/token:
    servers:
      - url: https://access.checkout.com
        description: Live API
      - url: https://access.sandbox.checkout.com
        description: Sandbox API
    post:
      summary: Request an access token
      tags: 
        - Access
      description: OAuth endpoint to exchange your access key ID and access key secret for an access token.
  /disputes:
    get:
      tags:
        - Disputes
      security: 
        - OAuth: 
          - disputes
          - disputes:view
        # - ApiKey: []
      summary: Get disputes
      description: >-
        Returns a list of all disputes against your business. The results will be
        returned in reverse chronological order, showing the last modified dispute
        (for example, where you've recently added a piece of evidence) first. You
        can use the optional parameters below to skip or limit results.
  /disputes/{dispute_id}:
    get:
      tags:
        - Disputes
      security: 
        - OAuth: 
          - disputes
          - disputes:view
        # - ApiKey: []
      summary: Get dispute details
      description: Returns all the details of a dispute using the dispute identifier.
  /disputes/{dispute_id}/accept:
    post:
      tags:
        - Disputes
      security: 
        - OAuth: 
          - disputes
          - disputes:accept
        # - ApiKey: []
      summary: Accept dispute
      description: >-
        If a dispute is legitimate, you can choose to accept it. This will close it
        for you and remove it from your list of open disputes. There are no further
        financial implications.
  /disputes/{dispute_id}/evidence:
    put:
      tags:
        - Disputes
      security: 
        - OAuth: 
          - disputes
          - disputes:provide-evidence
        # - ApiKey: []
      summary: Provide dispute evidence
      description: >
        Adds supporting evidence to a dispute. Before using this endpoint, you first
        need to [upload your files](#tag/Disputes/paths/~1files/post) using the file
        uploader. You will receive a file id (prefixed by `file_`) which you can
        then use in your request.
        Note that this only attaches the evidence to the dispute, it does not send
        it to us. Once ready, you will need to submit it.
        **You must provide at least one evidence type in the body of your request.**
    get:
      tags:
        - Disputes
      security: 
        - OAuth: 
          - disputes
          - disputes:view
        # - ApiKey: []
      summary: Get dispute evidence
      description: >
        Retrieves a list of the evidence submitted in response to a specific
        dispute. 
    post:
      tags:
        - Disputes
      security: 
        - OAuth: 
          - disputes
          - disputes:provide-evidence
        # - ApiKey: []
      summary: Submit dispute evidence
      description: >-
        With this final request, you can submit the evidence that you have
        previously provided. Make sure you have provided all the relevant
        information before using this request. You will not be able to amend your
        evidence once you have submitted it.
  /files:
    post:
      tags:
        - Disputes
      security: 
        - OAuth: 
          - disputes
          - disputes:provide-evidence
        # - ApiKey: []
      summary: Upload file
      description: >-
        Upload a file to use as evidence in a dispute. Your file must be in either
        JPEG/JPG, PNG or PDF format, and be no larger than 4MB.
  /files/{file_id}:
    get:
      tags:
        - Disputes
      security: 
        - OAuth: 
          - disputes
          - disputes:view
        # - ApiKey: []
      summary: Get file information
      description: Retrieve information about a file that was previously uploaded.
  /workflows:
    get:
      security:
        - OAuth:
          - flow
          - flow:workflows
      tags:
        - Workflows
      summary: Get all workflows
      description: |
        Get all workflows
    post:
      security:
        - OAuth:
          - flow
          - flow:workflows
      tags:
        - Workflows
      summary: Add a workflow
      description: |
        Add a new Flow workflow
  /workflows/{workflowId}:
    get:
      security:
        - OAuth:
            - flow
            - flow:workflows
      tags:
        - Workflows
      summary: Get a workflow
      description: |
        Get the details of a workflow
    # put:
    #   servers:
    #     - url: http://flow.cko.lon/client
    #       description: QA
    #   security:
    #     - OAuth:
    #         - flow
    #         - flow:workflows
    #   tags:
    #     - Workflows
    #   summary: Update a workflow
    #   description: |
    #     Update a workflow
    #   parameters:
    #     - in: path
    #       name: workflowId
    #       schema:
    #         type: string
    #         pattern: ^wf_[a-z0-9]{26}$
    #       required: true
    #       description: The workflow identifier
    #       example: wf_c7svxlvo2bbuva4f6s3xu4f7wm
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/add-workflow-request'
    #   responses:
    #     '201':
    #       description: Workflow updated successfully
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/add-workflow-response'
    #       headers:
    #         Cko-Request-Id:
    #           schema:
    #             $ref: "#/components/headers/Cko-Request-Id"
    #         Cko-Version:
    #           schema:
    #             $ref: "#/components/headers/Cko-Version"
    #     '401':
    #       description: Unauthorized
    #     '404':
    #       description: Workflow not found 
    #     '500':
    #       description: Internal Error
    
    delete:
      tags:
        - Workflows
      summary: Remove a workflow
      description: |
        Removes a workflow so it is no longer being executed. 
        Actions of already executed workflows will be still processed.
  /workflows/event-types:
    get:
      security:
        - OAuth:
          - flow
          - flow:workflows
      tags:
        - Workflows
      summary: Get event types
      description: |
        Get a list of sources and their events for building new workflows
  /workflows/events/{eventId}:
    get:
      security:
        - OAuth:
          - flow
          - flow:events
      tags:
        - Workflows
      summary: Get an event
      description: |
        Get the details of an event
  /workflows/events/subject/{subjectId}:
    get:
      security:
        - OAuth:
          - flow
          - flow:events
      tags:
        - Workflows
      summary: Get subject events
      description: |
        Get all events that relate to a specific subject
  /forex/quotes:
    post:
      tags:
        - Forex
      security: 
        - OAuth: 
          - fx
      summary: Request a quote
      description: |
        Request an exchange rate between a source and destination currency pair that will be used to process one or more payouts. You must submit a payout with the FX quote identifier before the quote expires. If the FX quote identifier is omitted from a payout, and the source and destination currencies differ, the current market exchange rate will be used.
  /instruments:
    post:
      tags:
        - Instruments
      security: 
        - OAuth: 
          - vault
          - vault:instruments
      summary: Create an instrument
      description: |
        Create a bank account payment instrument that you can later use as the destination for one or more payouts. <br><br>The parameters you need to provide depend on the destination country and currency. See <a href="https://docs.checkout.com/pay-to-bank/payout-formatting" target="_blank">our docs</a> and the <a href="#tag/Instruments/paths/~1validation~1bank-accounts~1{country}~1{currency}/get">GET endpoint below</a>.
  /instruments/{id}:
    patch:
      tags:
        - Instruments
      security: 
        - OAuth: 
          - vault
          - vault:instruments
      summary: Update an instrument
      description: |
        Update a bank account payment instrument that you can later use as the destination for one or more payouts.
    delete:
      tags:
        - Instruments
      security: 
        - OAuth: 
          - vault
          - vault:instruments
      summary: Delete an instrument
      description: |
        Delete a payment instrument.
  /marketplace/entities:
    post:
      description: |
        Onboard a sub-entity, so they can start receiving payments. Upon creation, Checkout.com will run due diligence checks. 
        If the checks are successful, the payment capabilities for the sub-entity will be enabled and they can start receiving payments.
      summary: Onboard a sub-entity
      security:
        - OAuth:
          - marketplace
      tags:
        - Marketplace
  /marketplace/entities/{id}:
    get:
      summary: Get sub-entity details
      security:
        - OAuth:
          - marketplace
      tags:
        - Marketplace
    put:
      description: |
        You can update all fields under the ContactDetails, Profile, and Company objects. 
        Please note that when you update a sub-entity we may conduct further due diligence checks when necessary. During these checks, your payment capabilities will remain the same.
      summary: Update sub-entity details
      security:
        - OAuth:
          - marketplace
      tags:
        - Marketplace
  /payments:
    post:
      security:
        - ApiSecretKey: []
      tags:
        - Payments
      summary: Request a payment or payout
      operationId: requestAPaymentOrPayout
      description: |
        Send a payment or payout 
  /payments/{id}:
    get:
      tags:
        - Payments
      security: 
        - OAuth: 
          - gateway
          - gateway:payment-details
        # - ApiKey: []
      summary: Get payment details
      description: |
        Returns the details of the payment with the specified identifier string.
    
        If the payment method requires a redirection to a third party (e.g., 3D Secure),
        the redirect URL back to your site will include a `cko-session-id` query parameter
        containing a payment session ID that can be used to obtain the details of the payment, for example:
    
        http://example.com/success?cko-session-id=sid_ubfj2q76miwundwlk72vxt2i7q.
  /payments/{id}/actions:
    get:
      tags:
        - Payments
      security: 
        - OAuth: 
          - gateway
          - gateway:payment-details
        # - ApiKey: []
      summary: Get payment actions
      description: |
        Returns all the actions associated with a payment ordered by processing date in descending order (latest first).
  /payments/{id}/authorizations:
    post:
      tags:
        - Payments
      security: 
        - OAuth: 
          - gateway
          - gateway:payment-authorizations
        # - ApiKey: []
      summary: Increment authorization
      description: |
        Request an incremental authorization to increase the authorization amount or extend the authorization's validity period (Mastercard only).
    
  /payments/{id}/captures:
    post:
      tags:
        - Payments
      security: 
        - OAuth: 
          - gateway
          - gateway:payment-captures
        # - ApiKey: []
      summary: Capture a payment
      description: |
        Captures a payment if supported by the payment method.
    
        For card payments, capture requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the capture is successful.
  /payments/{id}/refunds:
    post:
      tags:
        - Payments
      security: 
        - OAuth: 
          - gateway
          - gateway:payment-refunds
        # - ApiKey: []
      summary: Refund a payment
      description: |
        Refunds a payment if supported by the payment method.
    
        For card payments, refund requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the refund is successful.
  /payments/{id}/voids:
    post:
      tags:
        - Payments
      security: 
        - OAuth: 
          - gateway
          - gateway:payment-voids
        # - ApiKey: []
      summary: Void a payment
      description: |
        Voids a payment if supported by the payment method.
    
        For card payments, void requests are processed asynchronously. You can use [workflows](#tag/Workflows) to be notified if the void is successful.
  /sessions:
    post:
      tags:
        - Sessions
      security:
        - OAuth:
          - sessions:app
          - sessions:browser
      summary: Request a session
      description: |
        Create a payment session to authenticate a cardholder before requesting a payment.
        Payment sessions can be linked to one or more payments (in the case of recurring and other merchant-initiated payments).
    
        The `next_actions` object in the response tells you which actions can be performed next. 
    
  /sessions/{id}:
    get:
      tags:
        - Sessions
      security:
        - OAuth:
          - sessions:app
          - sessions:browser
        - SessionSecret: []
      summary: Get session details
      description: |
        Returns the details of the session with the specified identifier string.
  /sessions/{id}/collect-data:
    put:
      security:
        - SessionSecret: []
      summary: Update a session
      description: Update a session by providing information about the environment.
      tags:
        - Sessions
  /sessions/{id}/complete:
    post:
      security:
        - SessionSecret: []
      summary: Complete a session
      description: |
        Completes a session by posting the the following request to the callback URL (only relevant for non hosted sessions):
        ```
        {
           "session_id": "sid_llraltf4jlwu5dxdtprcv7ba5i",
           "amount" : 6540,
           "currency": "USD",
           "status": "approved",
           "authentication_type": "regular",
           "authentication_category": "payment",
           "reference": "ORD-5023-4E89",
           "approved": true,
           "protocol_version": "2.1.0",
           "response_code": "Y",
           "response_reason": "01",
           "cryptogram": "MTIzNDU2Nzg5MDA5ODc2NTQzMjE=",
           "eci": "05",
           "xid": "XSUErNftqkiTdlkpSk8p32GWOFA",
           "cardholder_info": "Card declined. Please contact your issuing bank.",
           "challenged": true
        }
        ```
        <br/>
        The fields of the above are the same as they would be in a GET session response
      tags:
        - Sessions
  /sessions/{id}/issuer-fingerprint:
    put:
      security:
        - SessionSecret: []
      summary: Update session 3DS Method completion indicator
      description: Update the session's 3DS Method completion indicator based on the result of accessing the 3DS Method URL.
      tags:
        - Sessions
  /tokens:
    post:
      tags:
        - Tokens
      security: 
        - ApiPublicKey: []
      summary: Request a token
      description: |
        Exchange card details for a reference token that can be used later to request a card payment. Tokens are single use and expire after 15 minutes. 
        To create a token, please authenticate using your public key. 
    
        **Please note:** You should only use this for testing purposes.
  /validation/bank-accounts/{country}/{currency}:
    get:
      tags:
        - Instruments
      security: 
        - OAuth: 
          - payout:bank-details
      summary: Get bank account field formatting
      description: |
        Returns the bank account field formatting required to create bank account instruments or perform payouts for the specified country and currency.
components:
  securitySchemes:
    ApiPublicKey:
      description: >
            Unless explicitly stated, all endpoints require authentication using OAuth. 
            Public keys should only be used in JavaScript or native applications.
            
            #### Format
      
            - Sandbox `pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxx`
      
            - Production `pk_xxxxxxxxxxxxxxxxxxxxxxxxxx`
      name: Authorization
      type: apiKey
      in: Header
    OAuth:
      type: oauth2
      description: |
        For server-to-server communication, we support the OAuth 2.0 client credentials flow.
        We will provide you with a set of access key credentials – an access key ID and secret – which you can exchange for an access token by calling the 'request an access token' endpoint below. 
        You will need to authenticate using basic authentication, using your access key ID and access key secret as your username and password:
      
        ```
        curl --location --request POST 'https://access.checkout.com/connect/token' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --header 'Authorization: Basic dGVzdC1hY2Nlc3Mta2V5LWlkOnRlc3QtYWNjZXNzLWtleS1zZWNyZXQ=' \
        --data-urlencode 'grant_type=client_credentials' \
        --data-urlencode 'scope=gateway'
        ```
      
        The token server will return a Bearer `access_token` in JSON Web Token (JWT) format which you should use in the `Authorization`
        header of your API requests:
      
        ```
        curl --location --request POST 'https://api.checkout.com/payments' \
        --header 'Content-Type: application/json' \
        --header 'Accept: application/json' \
        --header 'Authorization: Bearer {{AccessToken}}' \
        --data-raw '{
          "amount": 10000,
          "currency": "USD",
          "reference": "Visa-USD-Test",
          ...
        }'
        ```
      
        Your access token will be valid for a length of time (in seconds) indicated by the `expires_in` field in the response. When it expires, you'll need to request a new one.
      
        Depending on the Environment against which you're making your requests against you'll need to request the token from a different Authorization Server.
      
        | Environment   |      Authorization Server                            |
        |---------------|------------------------------------------------------|
        | Sandbox       |  https://access.sandbox.checkout.com/connect/token   |
        | Production    |  https://access.checkout.com/connect/token           |
      
      flows:
        clientCredentials:
          tokenUrl: See table above
          scopes:
            vault: Access to all Vault resources
            "vault:instruments": Create instruments
            gateway: Access to all Gateway resources
            "gateway:payment": Request payments
            "gateway:payment-details": Get payment details
            "gateway:payment-authorizations": Increment authorizations
            "gateway:payment-voids": Void payments
            "gateway:payment-captures": Capture payments
            "gateway:payment-refunds": Refund payments
            "fx": Foreign exchange services
            "payouts:bank-details": Get bank details
            sessions: Access to all Sessions resources
            "sessions:app": App-based authentication
            "sessions:browser": Browser-based authentication
            disputes: Access to all Disputes resources
            "disputes:view": View disputes
            "disputes:provide-evidence": Provide dispute evidence
            "disputes:accept": Accept disputes
            martketplace:  Manage sub-entities
            flow: Access to all Flow resources
            "flow:workflows": Manage workflows
            "flow:events": Retrieve events
    SessionSecret:
      description: >
            A base64 encoded value prefixed with `sek_` that gives access to client-side operations for a single authentication within the Sessions API. This value is returned as the `session_secret` when requesting a session. 
      name: Authorization
      type: apiKey
      in: Header
      maxLength: 48